Repository FppEpitech/Gomoku, pull requests merged in 2024-11, with the labels that each got.

#6 FEAT: Create Makefile and folder
  Makefile
  src/main.py
Labels: enhancement, project struct

#7 FEAT: Adding contributing md
  Contributing.md
Labels: documentation

#9 FEAT: Add issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#10 REFACTOR: architecture
  .github/workflows/mirror.yml
  .gitignore
  Makefile
  config.ini
  tests/config.ini
  tests/example_enemy/pbrain-enemy2.py
  tests/liskvork-bin
Labels: enhancement, project struct

#12 FEAT: Create map structure
  src/Map/map.py
Labels: enhancement, project struct

#13 Feat: Create communication protocol
  Makefile
  config.ini
  src/Map/map.py
  src/communication/command/about.py
  src/communication/command/begin.py
  src/communication/command/board.py
  src/communication/command/end.py
  src/communication/command/info.py
  src/communication/command/start.py
  src/communication/command/turn.py
  src/communication/parser.py
  src/main.py
  tests/config.ini
Labels: enhancement, protocol

#16 FEAT: Add Game rules class
  src/Game_rules/game_rules.py
  src/Map/map.py
  src/communication/command/begin.py
  src/communication/command/board.py
  src/communication/command/info.py
  src/communication/command/start.py
  src/communication/command/turn.py
  src/communication/parser.py
  src/main.py
Labels: enhancement, protocol

#18 TEST: Easy win and lose
  Makefile
  src/Map/map.py
  src/communication/command/board.py
  tests/config.ini
  tests/create_boards/create_boards.py
  tests/easy_lose/test_easy_lose.py
  tests/easy_win/test_easy_win.py
  tests/tests.py
Labels: tests

#20 FEAT: Win and Loose condition
  Makefile
  src/Map/map.py
  src/communication/command/begin.py
  src/communication/command/board.py
  src/communication/command/turn.py
  tests/easy_lose/test_easy_lose.py
  tests/easy_win/test_easy_win.py
Labels: enhancement, AI

#22 REFACTOR: Replace Python files into CPP files
  Makefile
  src/GameRules/GameRules.hpp
  src/GameRules/GamesRules.cpp
  src/Game_rules/game_rules.py
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Map/map.py
  src/Parser/Parser.cpp
  src/Parser/Parser.hpp
  src/algorithm/ai.py
  src/algorithm/mini_max.py
  src/communication/command/about.py
  src/communication/command/begin.py
  src/communication/command/board.py
  src/communication/command/end.py
  src/communication/command/info.py
  src/communication/command/start.py
  src/communication/command/turn.py
  src/communication/parser.py
  src/main.cpp
  src/main.py
  tests/easy_lose/test_easy_lose.py
  tests/easy_win/test_easy_win.py
Labels: project struct

#27 FEAT: Evaluation function
  .gitignore
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Parser/Parser.cpp
Labels: enhancement, AI

#31 FEAT: Minimax implementation
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Parser/Parser.cpp
  src/Parser/Parser.hpp
Labels: enhancement, AI

#32 TESTS: Win condition/ Avoid loose
  Makefile
  tests/avoid_lose/test_avoid_loose.cpp
  tests/config.ini
  tests/create_boards/create_boards.py
  tests/easy_lose/test_easy_lose.py
  tests/easy_win/test_easy_win.cpp
  tests/easy_win/test_easy_win.py
  tests/example_enemy/pbrain-enemy2.py
  tests/ia/pbrain-gomoku-Random-ai
Labels: tests

#33 REFACTOR: Change depth
  src/Map/Map.cpp
  src/Map/Map.hpp
Labels: AI

#36 FEAT: Add a move to block a line of four of ennemy
  Makefile
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Map/canAlign.cpp
Labels: enhancement, AI

#43 REFACTOR: Mini refactors in the project.
  README.md
  bonus/old_python/ai.py
  bonus/old_python/mini_max.py
  src/Algorithms/.gitkeep
Labels: enhancement

#45 REFACTOR: Put algorithm in its own folder / structure.
  .gitignore
  Makefile
  src/Algorithms/Algorithm.cpp
  src/Algorithms/Algorithm.hpp
  src/Algorithms/evaluation.cpp
  src/Algorithms/miniMax.cpp
  src/Map/Map.cpp
  src/Map/Map.hpp
Labels: enhancement

#46 feat: CI runing make and make tests and making fight ai between them
  .github/workflows/check.yml
  .github/workflows/fight.yml
  .gitignore
  Makefile
  tests/config-aiv1-run.ini
Labels: ci / cd

#48 FEAT: Avoid and Win Line of Four
  Makefile
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Map/winLineFour.cpp
  tests/complexPattern/test_lineFour.cpp
Labels: enhancement, AI

#50 FEAT: Create graphical application
  bonus/graphical/Assets/Player1.png
  bonus/graphical/Makefile
  bonus/graphical/config.ini
  bonus/graphical/liskvork-bin
  bonus/graphical/src/GameRules/GameRules.hpp
  bonus/graphical/src/GameRules/GamesRules.cpp
  bonus/graphical/src/GraphicLib/GraphicLib.cpp
  bonus/graphical/src/GraphicLib/GraphicLib.hpp
  bonus/graphical/src/Map/Map.cpp
  bonus/graphical/src/Map/Map.hpp
  bonus/graphical/src/Parser/Parser.cpp
  bonus/graphical/src/Parser/Parser.hpp
  bonus/graphical/src/Rules.hpp
  bonus/graphical/src/main.cpp
Labels: enhancement

#53 REFACTOR: Winning line of three
  src/Map/winLineFour.cpp
  tests/complexPattern/test_lineFour.cpp
Labels: AI

#55 FIX: Revert branch of timeout
  src/Algorithms/Algorithm.hpp
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Map/canAlign.cpp
  src/Map/winLineFour.cpp
  src/Map/winPatterns.cpp
Labels: enhancement, AI

#59 FEAT: Score pattern creation in evaluation function
  .gitignore
  Makefile
  src/Algorithms/.gitkeep
  src/Algorithms/Algorithm.hpp
  src/Algorithms/evaluation.cpp
  src/Algorithms/miniMax.cpp
  src/Map/Map.hpp
  src/Map/winPatterns.cpp
  tests/createComplexPattern/test_createComplexPattern.cpp
  tests/ia/pbrain-gomoku-ai-v2
Labels: AI

#61 FEAT: block square of ennemy
  Makefile
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Map/winSquare.cpp
  tests/complexPattern/test_squarePatern.cpp
Labels: enhancement

#66 REFACTOR: Gomoku add -O3
  Makefile
  src/Algorithms/Algorithm.hpp
  src/Map/Map.cpp
Labels: enhancement

#68 FIX: Dumb moves
  src/Algorithms/Algorithm.hpp
  src/Algorithms/evaluation.cpp
  src/Map/Map.cpp
  src/Map/Map.hpp
  src/Map/winSquare.cpp
Labels: AI
